### ISSUE TITLE
arrowhead issue

### ISSUE THREAD

**Issue by Antony-1996** [theaidenlab/juicer#115]
hello ，I have encounter a problem when I use arrowhead .it shows the error like this
![image](https://user-images.githubusercontent.com/43497334/58333386-ddd98300-7e6f-11e9-96bc-2becbbd33268.png)
Dose anybody know what is wrong?

**Comment by sa501428** [comment]
Hey @Antony-1996 , yes - this error is occuring because you used the newest jar to build the hic file, but you're running arrowhead with an older jar. We had a significant upgrade in version 1.10.XX allowing for new normalization vectors to be added. If you use the latest jar to run Arrowhead, this should work. Please let us know.

**Comment by Antony-1996** [comment]
thanks，it work fluently 。
