### ISSUE TITLE
Option: <specified_loop_list> doesn't work in CPU Version HiCCUPs 

### ISSUE THREAD

**Issue by lux563624348** [theaidenlab/juicer#125]
**Describe the bug**
Format of HiCCUPs command: 
hiccups  [-d centroid distances] [HiC file] [outputDirectory] [specified_loop_list]

And it says and I quoted from Usage page: "The CPU version of HiCCUPS uses exactly the same inputs (including all the optional parameters) as regular HiCCUPS, with the addition of the --cpu flag."

But it returns the same output whether I attached <specified_loop_list> when --cpu flag on. 

**To Reproduce**
hiccups --cpu -t 36 --ignore_sparsity  ./xx.hic ./output_Directory ./specified_loop_list.bedpe
returns same output as hiccups --cpu -t 36 --ignore_sparsity  ./xx.hic ./output_Directory 

**Expected behavior**
It should return the enrichments for these specified loops (./specified_loop_list.bedpe).

**Desktop (please complete the following information):**
 - OS: [linux 18.04]

**Comment by sa501428** [comment]
@lux563624348 to clarify, your output folder contains no `requested_list[...].bedpe` file?

**Comment by lux563624348** [comment]
> @lux563624348 to clarify, your output folder contains no `requested_list[...].bedpe` file?
Thank you for your reponse,
Actually it does, I can find requested_list with different resolution.  But my input for [specified_loop_list] is output file "merged_loops.bedpe" from one library. Can I get the results on those loops?

**Comment by sa501428** [comment]
requested_list[...] should contain the results for the loops from the other library. Can you check the content and confirm?

**Comment by lux563624348** [comment]
> requested_list[...] should contain the results for the loops from the other library. Can you check the content and confirm?
Thank you for following up reply. 

For exmaple:
I expected that if I use of "Top_10_loopslists.bedpe" as input for [specified_loop_list], I should get the new results in the same coordinates as these Top_10_loopslists.bedpe. Please correct me if I am wrong.

Real Case:
Now, My input contains (11,511 loops) for [specified_loop_list]. But the number of loops in requested_list[5000, 10000, 25000] are 9858, 9269 and 7469 seperately. None of them matches 11,511. 

According to the structure in output directory of HiCCUPs, shall I have something like merge_loops_requested_list.bedpe?

Thanks

**Comment by sa501428** [comment]
This is not exactly how the code runs, but I've pushed some updates (considering this an enhancement).

In prior versions, it processed the given list and found enrichment values at the specified pixels for each resolution. CPU version only searches near the diagonal (in order to run in a reasonable amount of time), so it will not include regions far from the diagonal (hence different numbers at different resolutions). We also don't merge the given pixels by default as they aren't always loops. 

However, in the latest version (1.12.03), I've pushed an update to (1) post-process the given list at each resolution and (2) merge the results across resolutions. This will create additional files besides the ones created prior.

You can try it here:
https://github.com/aidenlab/Juicer/wiki/Download#version-11203

Note - this may not be desired for certain analyses.

**Comment by lux563624348** [comment]
> This is not exactly how the code runs, but I've pushed some updates (considering this an enhancement).
> 
> In prior versions, it processed the given list and found enrichment values at the specified pixels for each resolution. CPU version only searches near the diagonal (in order to run in a reasonable amount of time), so it will not include regions far from the diagonal (hence different numbers at different resolutions). We also don't merge the given pixels by default as they aren't always loops.
> 
> However, in the latest version (1.12.03), I've pushed an update to (1) post-process the given list at each resolution and (2) merge the results across resolutions. This will create additional files besides the ones created prior.
> 
> You can try it here:
> https://github.com/aidenlab/Juicer/wiki/Download#version-11203
> 
> Note - this may not be desired for certain analyses.

Appreciate it.
