### ISSUE TITLE
how use juicer to produce a matrix file like this

### ISSUE THREAD

**Issue by ZQY19960810** [theaidenlab/juicer#274]
dear author:
I want to produce a matrix file as follow:
![1647860329(1)](https://user-images.githubusercontent.com/76091271/159247931-572dac7a-82b9-4bd4-8d7f-e1f0c058bb7f.png)
I don't know how to do that,maybe is a matrix extract per pos counts
please let me know if you know the answer 
thank you

**Comment by sa501428** [comment]
Yes this is supported. You can convert this representation to the short format. Keep in mind that since the matrix is symmetric, you only should provide the upper triangular matrix. (don't duplicate entries both above and below the diagonal) 
https://github.com/aidenlab/juicer/wiki/Pre#short-with-score-format

**Comment by qianyizhaoooo** [comment]
so I understand you that is a o/e matrix, I found juicertools dump can extract o/e score from offered .hic file  , but  I noticed it can only caclculate single  chromosome socre , what I want is the o/e matrix of whole genome. Please tell me how to do that , thanks very much

**Comment by sa501428** [comment]
The o/e matrix of the whole genome is not a well-defined operation for several reasons, including
- expected model for intra vs inter are very different
- inter expected is very sensitive to sparsity
- sparsities of intra vs inter are not uniform
