### ISSUE TITLE
fatal: cannot open source file `/public/home/qczhang/WSY/juicer/scripts/common/chimeric_blacklist.awk' for reading: No such file or directory

### ISSUE THREAD

**Issue by fire-activate** [theaidenlab/juicer#280]
I have a issues please please answer me 
fatal: cannot open source file `/public/home/qczhang/WSY/juicer/scripts/common/chimeric_blacklist.awk' for reading: No such file or directory
***! Failure during chimera handling of /public/home/qczhang/WSY/juicer/work/FH/splits/FDHC202177148_.fastq.gz

**Comment by pna059** [comment]
Same problem here. The pipeline stops after alignment due to a missing-differently named script for chimera handling. I plastered this by copying the chimera_blacklist.awk to the CPU/common directory.

**Comment by fire-activate** [comment]
> 

Thank you ，I have solved this problem。

**Comment by dandanWang2019** [comment]
Hi hi,

I encountered the same problem, and checked the original code of juicer.sh, which only use "$JUICER/scripts/chimeric_blacklist.awk", without "common" in the path, a little confused about where "common" introduced in the code.

**I set -D using user/software/juicer/SLURM, is there anything wrong with the path?** Because there is no folder names "common", which I need to create under SLURM/scripts, and then copy chimeric_blacklist.awk there. Is this the same situation as yours?

Thanks a lot
