### ISSUE TITLE
juicer on PBS, first job terminated then remaining jobs are orphaned

### ISSUE THREAD

**Issue by jstansfield0** [theaidenlab/juicer#39]
After the update to the PBS version of the juicer scripts I am able to run juicer.sh. However now all the jobs are created but the first job for some reason terminates and ends up causing the remaining jobs to become orphans. I am just trying it on the small test data set provided in the wiki.

When I first run juicer.sh it creates 5 jobs seen here:
```
Job id            Name             User              Time Use S Queue
----------------  ---------------- ----------------  -------- - -----
207555.merlot     AlnWrpC18126     stansfieldjc             0 R workq
207556.merlot     MStWrpC18126     stansfieldjc             0 H workq
207557.merlot     RDpWrpC18126     stansfieldjc             0 H workq
207558.merlot     SpWrp1C18126     stansfieldjc             0 H workq
207561.merlot     SpWrp2C18126     stansfieldjc             0 H workq
```

I then get the following email from the cluster after a minute or two:
PBS Job Id: 207556.merlot.bis.vcu.edu
Job Name:   MStWrpC18126
Aborted by PBS Server
Job deleted as result of dependency on job 207555.merlot.bis.vcu.edu

And after that the remaining 3 jobs remain orphaned and on hold.

I then got the next email from the cluster:

PBS Job Id: 207555.merlot.bis.vcu.edu
Job Name:   AlnWrpC18126
Post job file processing error; job 207555.merlot.bis.vcu.edu on host node10

Do you know what is going on here or how I can fix it?

**Comment by mzhibo** [comment]
This is a bug.
when I modified this script, the AlnWrp job will start after the fastq splitting job. The fastq splitting job will only be place when if [ -n "$threads" ] && [ -z "$skipsplit" ] is true.
threads is only determined based on your fastq file size.
if [ "$fastqsize" -gt "2592410750" ]
then
    threads=16
fi
So, if you use a fastq file larger than 2592410750. I will work fine.
I will modify the script and upload the updated one in a few moment.
Thanks 
Zhibo

**Comment by mzhibo** [comment]
It might be due to your test fastq file size being smaller than the settings for multi-threads setting. see below:
if [ "$fastqsize" -gt "2592410750" ]
then
    threads=16
fi

When i build the dependencies, I set the AlnWrp to work after the fastq splitting and mv jobs.
in AlnWrp job submission: #PBS -W depend=afterok:${jID_splitmv}
The job splitting and mv jobs is only placed when this if [ -n "$threads" ] && [ -z "$skipsplit" ] test is ture.

So, it will be fine if you work with fastq files larger than 2592410750

You can add the following lines between the hash tag lines
############################
    if [ -n "$threads" ] && [ -z "$skipsplit" ] 
    then
         waitstring_alnwrp="#PBS -W depend=afterok:${jID_splitmv}"
    fi	
    echo "waitstring_alnwrp is ${waitstring_alnwrp}"
#####################
in front of the ALINWRAP job script (right before the following block.)
    timestamp=$(date +"%s" | cut -c 4-10)
    qsub <<ALIGNWRAP
    #PBS -S /bin/bash
    #PBS -q $queue
    #PBS -l $walltime
    #PBS -l nodes=1:ppn=1:AMD
    #PBS -l mem=6gb
    #PBS -o ${logdir}/${timestamp}_alnwrap_${groupname}.log
    #PBS -j oe
    #PBS -N AlnWrp${groupname}
    $waitstring_alnwrp
    ${EMAIL}
    #PBS -m a

I will also upload the new updated version. You can download the new juicer.sh launch_stats.sh and postprocessing.sh files from the github once the admin accepts the pull request.
I also fixed another bug this morning in postprocessing.sh.
Zhibo
@jstansfield0

**Comment by mzhibo** [comment]
Also check the log file in logs directory. If my previous guess is true, then the ${logdir}/${timestamp}_alnwrap_${groupname}.log file should tell you something about qsub -W error.
Zhibo

**Comment by jstansfield0** [comment]
From the log file:

[190]stansfieldjc@merlot/home/sequencing/juicer/logs % cat
6519501_alnwrap_C19501.log
qsub: Bad UID for job execution
jID_cntlig 1 id is
/var/spool/PBS/mom_priv/jobs/207474.merlot.bis.vcu.edu.SC: line 64: * 5 :
syntax error: operand expected (error token is "* 5 ")
qsub: Bad UID for job execution
qsub: Bad UID for job execution

**Comment by mzhibo** [comment]
@jstansfield0 
it seems to be a problem that your cluster does not allow jobs to be submitted from computer nodes other than the login node. 
The cluster in our school allows us to submit jobs from all the computer nodes. 
I would suggest you to contact your culster team to see if then have any good suggestions.
I also just started to use linux and PBS, sorry I can't help more.
this link might be related to your issue.
https://lists.sdsc.edu/pipermail/npaci-rocks-discussion/2002-August/000211.html
Zhibo

**Comment by mzhibo** [comment]
The AlnWrp job was submitted and run on a computer node. This job will submit several other jobs. From your log file, it looks like the AlnWrp job was started successfully, but the qsub commands in AlnWrp job failed to run due to bad user ID error. This is usually due to the set-up of cluster that does not allow user to submit jobs from computer nodes other than the qlogin node.

**Comment by theaidenlab** [comment]
Let us know if this has been resolved.

**Comment by jstansfield0** [comment]
We have not been able to resolve the issue. Our cluster does not allow for jobs to be submitted from a node so the script does not work.

**Comment by nchernia** [comment]
Closing as we won't be able to resolve since we don't have access to PBS
