### ISSUE TITLE
Juicer stats jobs seem to get stuck on low complexity data

### ISSUE THREAD

**Issue by HelenLong1** [theaidenlab/juicer#75]
Hi, 

I think I have identified a bug which appears when attempting to run juicer on fastq files after reads which do not meet the MAPQ<=30 threshold and duplicate reads have already been filtered out.

I have randomly down sampled a pre- filtered fastq file to 50M, 100M, 200M, 300M, 400M, 500M, 600M, 700M, 800M and 900M read pairs. As I have removed duplicate reads and reads which do not meet the MAPQ<=30 threshold before running juicer the complexity estimate of these samples should be zero. 

I am finding that at 50M, 100M, 200M, 300M, 800M read pairs the pipeline ran as expected. However, for 400M, 500M, 600M, 700M, 900M read pairs the stats jobs get stuck after printing the number of "Optical Duplicates" and then never finish. Despite the stats jobs never finishing (and the output of the stats jobs being truncated) the .hic files are created, I receive the expected "pipeline complete" message and the only errors in the debug folders (grep "Error" debug/*) are: 

debug/hic-a1535292471.err:Error while reading graphs file: java.io.FileNotFoundException: /Blymphoblasts/500Mdownsample/aligned/inter_hists.m (No such file or directory)
debug/hic30-a1535292471.err:Error while reading graphs file: java.io.FileNotFoundException: /Blymphoblasts/500Mdownsample/aligned/inter_30_hists.m (No such file or directory)

I have no idea what is causing the stats jobs to get stuck in some samples and not others. It seems that the stats jobs are more likely to get stuck if there are a large number of read pairs. I have also noticed that in all of the samples that run without problem there were no PCR duplicates detected and in all the samples in which the stats jobs got stuck at least one PCR duplicate was detected. 

I have attached the outputs from the stats jobs for each sample. 

[downsampling_inter.txt](https://github.com/theaidenlab/juicer/files/2361229/downsampling_inter.txt)
[downsampling_inter_30.txt](https://github.com/theaidenlab/juicer/files/2361230/downsampling_inter_30.txt)

Best wishes, 

Helen

**Comment by nchernia** [comment]
@sa501428 is this fixed in the Juicer Tools version?

Also we should probably update Juicer to no longer use LibraryComplexity - right?

**Comment by nchernia** [comment]
We have added in a flag for this: 

Flag -j for "just exact matches"; this will only eliminate exact match duplicates. Overall this flag is not recommended. However, if you find your jobs are often getting stuck at the dedup phase, it can be because of low complexity or low mapping quality and this flag will allow the jobs to finish much faster. You will still be left with near-duplicates in your library - so use caution when interpreting results. In particular note that near-duplicates are usually machine errors, not true biological results, and thus ought to be removed.

We have also updated so that LibraryComplexity is no longer called
